# Generated by Django 4.2.2 on 2023-07-05 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import linkis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_endpoint', models.SlugField(null=True, unique=True)),
                ('profile_endpoint', models.SlugField(blank=True, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=140, null=True)),
                ('summary', models.CharField(blank=True, max_length=140, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Linki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('privacy', models.IntegerField(choices=[(0, 'Private'), (1, 'Unlisted'), (2, 'Public')], default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label_id', models.CharField(default='00000000000000000000000000000000000000000000000000000000', max_length=56, primary_key=True, serialize=False)),
                ('data', models.JSONField(decoder=linkis.models.StructDecoder, default=dict, encoder=linkis.models.StructEncoder)),
                ('privacy', models.IntegerField(choices=[(0, 'Private'), (1, 'Unlisted'), (2, 'Public')], default=1)),
                ('rendered_content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
