# Generated by Django 4.2.2 on 2023-07-09 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Linki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('privacy', models.IntegerField(choices=[(0, 'Private'), (1, 'Unlisted'), (2, 'Public')], default=1)),
                ('name', models.SlugField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('privacy', models.IntegerField(choices=[(0, 'Private'), (1, 'Unlisted'), (2, 'Public')], default=1)),
                ('id', models.CharField(default='00000000000000000000000000000000000000000000000000000000', editable=False, max_length=56, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('rendered_content', models.TextField()),
                ('name', models.SlugField()),
                ('linki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkis.linki')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('structs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_endpoint', models.SlugField(null=True, unique=True)),
                ('profile_endpoint', models.SlugField(blank=True, null=True, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=140, null=True)),
                ('summary', models.CharField(blank=True, max_length=140, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('privacy', models.IntegerField(choices=[(0, 'Private'), (1, 'Unlisted'), (2, 'Public')], default=1)),
                ('id', models.CharField(default='00000000000000000000000000000000000000000000000000000000', editable=False, max_length=56, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('rendered_content', models.TextField()),
                ('linki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linkis.linki')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('structs', django.db.models.manager.Manager()),
            ],
        ),
    ]
