# Generated by Django 4.2.2 on 2023-06-27 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('url_endpoint', models.SlugField(null=True, unique=True)),
                ('profile_endpoint', models.SlugField(
                    blank=True, null=True, unique=True)),
                ('display_name', models.CharField(
                    blank=True, max_length=140, null=True)),
                ('summary', models.CharField(blank=True, max_length=140, null=True)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Linki',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, max_length=140)),
                ('url_endpoint', models.SlugField(blank=True)),
                ('privacy', models.IntegerField(choices=[
                 (0, 'Private'), (1, 'Unlisted'), (2, 'Public')], default=1)),
                ('title', models.CharField(max_length=140)),
                ('content', models.TextField()),
                ('rendered_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('editor', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='linki',
            constraint=models.UniqueConstraint(models.F('editor'), models.F(
                'url_endpoint'), name='editor_linki_url_endpoint'),
        ),
    ]
