# Generated by Django 4.2.2 on 2023-07-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linki',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
