# Generated by Django 4.2.2 on 2023-06-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0002_paste_editor_paste_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=140),
            preserve_default=False,
        ),
    ]
