# Generated by Django 4.2.2 on 2023-06-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0005_update_renders'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='privacy',
            field=models.IntegerField(choices=[(0, 'Private'), (1, 'Unlisted'), (2, 'Public')], default=1),
        ),
    ]
