# Generated by Django 4.2.2 on 2023-06-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0007_paste_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='title',
            field=models.CharField(max_length=140),
        ),
    ]
