# Generated by Django 4.2.2 on 2023-06-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_id',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
