# Generated by Django 4.2.2 on 2023-06-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0010_profile_display_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_id',
            field=models.SlugField(blank=True),
        ),
    ]
