# Generated by Django 4.2.2 on 2023-06-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0011_profile_display_name_alter_profile_display_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='display_id',
            new_name='url_endpoint',
        ),
        migrations.AddField(
            model_name='paste',
            name='url_endpoint',
            field=models.SlugField(blank=True),
        ),
    ]
