# Generated by Django 4.2.2 on 2023-06-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0013_alter_profile_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paste',
            constraint=models.UniqueConstraint(models.F('editor'), models.F('url_endpoint'), name='editor_paste_url_endpoint'),
        ),
    ]
