# Generated by Django 4.2.2 on 2023-06-25 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pastes', '0015_alter_profile_url_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url_endpoint',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
