# Generated by Django 4.2.2 on 2023-06-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0016_alter_profile_display_name_alter_profile_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_endpoint',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
