# Generated by Django 4.2.2 on 2023-06-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0017_profile_profile_endpoint_alter_profile_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
