# Generated by Django 4.2.2 on 2023-06-26 00:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0022_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paste',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
