# Generated by Django 4.2.2 on 2023-06-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0003_alter_paste_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='rendered_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
