# Generated by Django 4.2.2 on 2023-06-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0014_paste_editor_paste_url_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url_endpoint',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
