# Generated by Django 4.2.2 on 2023-06-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastes', '0018_profile_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_name',
        ),
    ]
